"""
llm_client.py — OpenAI-compatible client pointing at local Ollama.
Uses llama3.1:8b for both step generation and final algorithm refinement.
"""

from openai import OpenAI
from . import config


_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(
            base_url=config.OLLAMA_BASE_URL,
            api_key=config.OLLAMA_API_KEY,
        )
    return _client


# ─────────────────────────────────────────────────────────────────────────────
# Step generation
# ─────────────────────────────────────────────────────────────────────────────

_STEP_SYSTEM = (
    "You are a technical documentation assistant. "
    "Given a raw UI action event and the UI element it targeted, "
    "write a single, concise step in an algorithm describing what the user did. "
    "Use imperative form (e.g. 'Click the Start button'). "
    "Output only the step text, no numbering, no extra explanation."
)

_STEP_USER_TMPL = """
Action event:
{action_json}

Matched UI element:
- Type    : {elem_type}
- Content : {elem_content}
- Position: center ({cx:.4f}, {cy:.4f}), size ({w:.4f} x {h:.4f}) [normalized 0-1]
- Match   : {match_method} (distance={distance:.4f})

Write the algorithm step.
""".strip()


def generate_step(action: dict, box_info: dict | None) -> str:
    """
    Generate a single natural-language algorithm step.

    Parameters
    ----------
    action : dict
        The full action record  { type, payload }.
    box_info : dict | None
        Result from event_processor.find_box():
        { bbox: [cx, cy, w, h], content, type, distance, match_method }
        Pass None when no screenshot was available.
    """
    import json

    if box_info:
        cx, cy, w, h = box_info["bbox"]
        user_msg = _STEP_USER_TMPL.format(
            action_json=json.dumps(action, indent=2),
            elem_type=box_info.get("elem_type", "unknown"),
            elem_content=box_info.get("content") or "(no label)",
            cx=cx, cy=cy, w=w, h=h,
            match_method=box_info.get("match_method", "euclidean"),
            distance=box_info.get("distance", 0.0),
        )
    else:
        # No screenshot / no box found — still generate a step from payload alone
        user_msg = (
            f"Action event (no screenshot available):\n"
            f"{json.dumps(action, indent=2)}\n\n"
            "Write the algorithm step."
        )

    response = _get_client().chat.completions.create(
        model=config.LLM_MODEL,
        temperature=config.LLM_TEMPERATURE,
        max_tokens=config.LLM_MAX_TOKENS,
        messages=[
            {"role": "system", "content": _STEP_SYSTEM},
            {"role": "user",   "content": user_msg},
        ],
    )
    return response.choices[0].message.content.strip()


# ─────────────────────────────────────────────────────────────────────────────
# Algorithm refinement (final pass)
# ─────────────────────────────────────────────────────────────────────────────

_REFINE_SYSTEM = (
    "You are a technical documentation expert. "
    "You receive a numbered list of steps that was automatically generated by "
    "recording a user's interaction with an operating-system GUI. "
    "Your job is to:\n"
    "1. Remove any steps that are clearly erroneous or redundant (e.g. opening "
    "   a window and immediately closing it, accidental clicks).\n"
    "2. Merge consecutive steps that are part of the same logical action "
    "   (e.g. multiple character keystrokes building a single word).\n"
    "3. Rewrite the remaining steps in clear, concise imperative English.\n"
    "4. Re-number the steps starting from 1.\n"
    "Output ONLY the numbered algorithm, nothing else."
)


def refine_algorithm(steps: list[str]) -> str:
    """
    Run a final LLM pass over all generated steps to clean up the algorithm.

    Parameters
    ----------
    steps : list[str]
        Raw algorithm steps, one per action.

    Returns
    -------
    str
        Polished, numbered algorithm text.
    """
    numbered = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
    user_msg = f"Here are the raw steps:\n\n{numbered}\n\nReturn the cleaned algorithm."

    response = _get_client().chat.completions.create(
        model=config.LLM_MODEL,
        temperature=config.LLM_TEMPERATURE,
        max_tokens=2048,
        messages=[
            {"role": "system", "content": _REFINE_SYSTEM},
            {"role": "user",   "content": user_msg},
        ],
    )
    return response.choices[0].message.content.strip()
